# RP2040-WIZNET-EAAS_BUILD_DEFINE: RP2040-WIZNET-EAAS_VERSION_MAJOR, SDK major version number
set(RP2040-WIZNET-EAAS_VERSION_MAJOR 1)
# RP2040-WIZNET-EAAS_BUILD_DEFINE: RP2040-WIZNET-EAAS_SDK_VERSION_MINOR, SDK minor version number
set(RP2040-WIZNET-EAAS_VERSION_MINOR 1)
# RP2040-WIZNET-EAAS_BUILD_DEFINE: RP2040-WIZNET-EAAS_SDK_VERSION_REVISION, SDK version revision
set(RP2040-WIZNET-EAAS_VERSION_REVISION 0)
# RP2040-WIZNET-EAAS_BUILD_DEFINE: RP2040-WIZNET-EAAS_SDK_VERSION_STRING, SDK version
set(RP2040-WIZNET-EAAS_VERSION_STRING "${RP2040-WIZNET-EAAS_SDK_VERSION_MAJOR}.${RP2040-WIZNET-EAAS_VERSION_MINOR}.${RP2040-WIZNET-EAAS_VERSION_REVISION}")

message(STATUS "RP2040-WIZNET-EAAS version is ${RP2040-WIZNET-EAAS_VERSION_STRING}")
